const $=s=>document.querySelector(s);const els={search:$('#productSearch'),suggestions:$('#suggestions'),qty:$('#quantity'),price:$('#selectedPrice'),selected:$('#selectedProduct'),items:$('#invoiceItems'),itemsCount:$('#itemsCount'),totalQty:$('#totalQty'),grand:$('#grandTotal'),toast:$('#toast')};
let products=[],customers=[],customerHistory=[],cart=[],selected=null,priceMode='wholesale',activeSuggestion=-1,deferredPrompt=null;const KEY='tawoos:pwa:invoices',PRODKEY='tawoos:pwa:products:v2';
const money=n=>Number(n||0).toLocaleString('ar-EG',{minimumFractionDigits:2,maximumFractionDigits:2});
function toast(msg){els.toast.textContent=msg;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),2400)}
function setDate(){const d=new Date();$('#invoiceDate').value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function normalize(s){return String(s||'').trim().toLocaleLowerCase('ar-EG')}
async function loadProducts(){try{const local=localStorage.getItem(PRODKEY);if(local)products=JSON.parse(local);else products=await (await fetch('products.json')).json();}catch(e){products=[];toast('تعذر تحميل المنتجات')}document.title=`Tawoos Invoice · ${products.length.toLocaleString('ar-EG')} منتج`}
async function loadCustomers(){try{customers=await (await fetch('customers.json')).json();customerHistory=await (await fetch('customer_history.json')).json()}catch(e){customers=[];customerHistory=[]}}
function renderCustomer(code){const c=customers.find(x=>String(x.code)===String(code).trim());const info=$('#customerInfo'),hist=$('#customerHistory');if(!c){info.classList.add('hidden');hist.classList.add('hidden');return}$('#customerName').value=c.name;$('#customerCity').value=c.city;info.classList.remove('hidden');info.innerHTML=`<strong>تم العثور على العميل:</strong> ${escapeHtml(c.name)} · ${escapeHtml(c.city||'بدون مدينة')} · ${escapeHtml(c.phone||'بدون هاتف')}`;const h=customerHistory.find(x=>String(x.customerCode)===String(code).trim());if(h&&h.items.length){hist.classList.remove('hidden');hist.innerHTML=`<div class="history-heading">مشتريات سابقة · ${h.invoiceCount} فاتورة</div><div class="history-chips">${h.items.slice(0,40).map(x=>`<button class="history-chip" data-code="${escapeHtml(x.code)}" title="إضافة بسعر ${x.mode==='wholesale'?'مستخدم 2':'مستخدم 3'}">${escapeHtml(x.name)} <small>${x.mode==='wholesale'?'مستخدم 2':'مستخدم 3'} · ${money(x.lastPrice)}</small></button>`).join('')}</div>`;hist.querySelectorAll('.history-chip').forEach(b=>b.addEventListener('click',()=>{const p=products.find(x=>String(x.code)===String(b.dataset.code));if(p)choose(p)}))}else hist.classList.add('hidden')}
function renderSuggestions(){const q=normalize(els.search.value);activeSuggestion=-1;if(!q){els.suggestions.classList.remove('open');els.suggestions.innerHTML='';return}const found=products.filter(p=>normalize(p.name).includes(q)||String(p.code).includes(q)).slice(0,40);els.suggestions.innerHTML=found.length?found.map((p,i)=>`<div class="suggestion" data-index="${i}" role="option"><span class="suggestion-name">${escapeHtml(p.name)}</span><span class="suggestion-meta">${escapeHtml(p.code)} · ${money(priceMode==='wholesale'?p.wholesale:p.retail)}</span></div>`).join(''):'<div class="suggestion"><span class="suggestion-name">لا توجد نتائج</span></div>';els.suggestions.classList.add('open');els.suggestions.querySelectorAll('.suggestion[data-index]').forEach(x=>x.addEventListener('mousedown',e=>{e.preventDefault();choose(found[Number(x.dataset.index)])}))}
function choose(p){selected=p;els.search.value=p.name;els.suggestions.classList.remove('open');els.selected.classList.remove('empty');els.selected.innerHTML=`<strong>${escapeHtml(p.name)}</strong> <span>· الكود ${escapeHtml(p.code)} · ${priceMode==='wholesale'?'مستخدم 2':'مستخدم 3'} ${money(priceMode==='wholesale'?p.wholesale:p.retail)}</span>`;updatePrice();els.qty.focus();els.qty.select()}
function updatePrice(){els.price.textContent=selected?money(priceMode==='wholesale'?selected.wholesale:selected.retail):'—';if(selected)els.selected.innerHTML=`<strong>${escapeHtml(selected.name)}</strong> <span>· الكود ${escapeHtml(selected.code)} · ${priceMode==='wholesale'?'مستخدم 2':'مستخدم 3'} ${money(priceMode==='wholesale'?selected.wholesale:selected.retail)}</span>`;document.querySelectorAll('.price-btn').forEach(b=>b.classList.toggle('active',b.dataset.price===priceMode));renderCart()}
function add(){if(!selected){toast('اكتب جزءًا من الاسم واختر منتجًا');els.search.focus();return}const qty=Number(els.qty.value);if(!qty||qty<=0){toast('أدخل كمية صحيحة');els.qty.focus();return}const existing=cart.find(x=>x.product.code===selected.code);if(existing)existing.qty+=qty;else cart.push({product:selected,qty});renderCart();els.search.value='';els.qty.value='1';selected=null;els.selected.textContent='لم يتم اختيار منتج';els.selected.classList.add('empty');els.price.textContent='—';els.search.focus()}
function renderCart(){if(!cart.length){els.items.innerHTML='<tr><td colspan="7" class="empty-row">لم تتم إضافة منتجات بعد</td></tr>'}else els.items.innerHTML=cart.map((x,i)=>{const w=x.product.wholesale*x.qty,r=x.product.retail*x.qty,p=priceMode==='wholesale'?w:r;return `<tr><td>${i+1}</td><td><strong>${escapeHtml(x.product.name)}</strong></td><td>${escapeHtml(x.product.code)}</td><td>${money(priceMode==='wholesale'?x.product.wholesale:x.product.retail)}</td><td><input class="line-qty" data-i="${i}" type="number" min=".01" step=".01" value="${x.qty}"></td><td><strong>${money(p)}</strong></td><td><button class="delete-line" data-i="${i}">حذف</button></td></tr>`}).join('');els.items.querySelectorAll('.line-qty').forEach(i=>i.addEventListener('change',()=>{const q=Number(i.value);if(q>0)cart[Number(i.dataset.i)].qty=q;renderCart()}));els.items.querySelectorAll('.delete-line').forEach(b=>b.addEventListener('click',()=>{cart.splice(Number(b.dataset.i),1);renderCart()}));const tq=cart.reduce((a,x)=>a+x.qty,0),total=cart.reduce((a,x)=>a+(priceMode==='wholesale'?x.product.wholesale:x.product.retail)*x.qty,0);els.itemsCount.textContent=`${cart.length.toLocaleString('ar-EG')} أصناف`;els.totalQty.textContent=tq.toLocaleString('ar-EG');els.grand.textContent=money(total)}
function invoiceData(){return {id:Date.now(),number:`TW-${String(Date.now()).slice(-6)}`,date:$('#invoiceDate').value,customerCode:$('#customerCode').value,customerName:$('#customerName').value,city:$('#customerCity').value,seller:$('#seller').value,section:$('#section').value,packageType:$('#packageType').value,packageCount:$('#packageCount').value,priceMode,cart}}
function save(){if(!cart.length){toast('أضف منتجًا واحدًا على الأقل');return}const all=JSON.parse(localStorage.getItem(KEY)||'[]');all.unshift(invoiceData());localStorage.setItem(KEY,JSON.stringify(all.slice(0,200)));renderSaved();toast('تم حفظ الفاتورة محليًا')}
function renderSaved(){const all=JSON.parse(localStorage.getItem(KEY)||'[]');$('#savedCount').textContent=all.length.toLocaleString('ar-EG');$('#savedInvoices').innerHTML=all.length?all.slice(0,12).map(x=>`<div class="saved-item"><div><strong>${escapeHtml(x.number)}</strong><small> · ${escapeHtml(x.customerName||'عميل نقدي')} · ${escapeHtml(x.date||'')}</small></div><div class="saved-actions"><button data-print="${x.id}">طباعة</button><button data-load="${x.id}">فتح</button></div></div>`).join(''):'<div class="empty-row">لا توجد فواتير محفوظة</div>';document.querySelectorAll('[data-load]').forEach(b=>b.addEventListener('click',()=>loadInvoice(Number(b.dataset.load))));document.querySelectorAll('[data-print]').forEach(b=>b.addEventListener('click',()=>{loadInvoice(Number(b.dataset.print));setTimeout(()=>window.print(),100)}))}
function loadInvoice(id){const x=JSON.parse(localStorage.getItem(KEY)||'[]').find(i=>i.id===id);if(!x)return;Object.entries({customerCode:x.customerCode,customerName:x.customerName,customerCity:x.city,seller:x.seller,section:x.section,packageType:x.packageType,packageCount:x.packageCount,invoiceDate:x.date}).forEach(([k,v])=>{if($('#'+k))$('#'+k).value=v||''});priceMode=x.priceMode||'wholesale';cart=x.cart||[];renderCart();updatePrice();toast('تم فتح الفاتورة')}
function newInvoice(){cart=[];selected=null;priceMode='wholesale';['customerCode','customerName','customerCity','seller'].forEach(id=>$('#'+id).value='');$('#packageCount').value='0';$('#packageType').value='';$('#section').value='بيتي';setDate();els.search.value='';els.qty.value='1';els.selected.textContent='لم يتم اختيار منتج';els.selected.classList.add('empty');updatePrice();els.search.focus()}
function exportData(){const data={products, invoices:JSON.parse(localStorage.getItem(KEY)||'[]'),createdAt:new Date().toISOString()};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='tawoos-backup.json';a.click();URL.revokeObjectURL(a.href)}
async function importFile(file){const text=await file.text();try{let data;if(file.name.toLowerCase().endsWith('.csv')){data=parseCsv(text).map(r=>({code:r[0],name:r[1],wholesale:Math.min(Number(r[4]||r[2]||0),Number(r[5]||r[3]||0)),retail:Math.max(Number(r[4]||r[2]||0),Number(r[5]||r[3]||0))}));}else{data=JSON.parse(text);data=data.products||data}if(!Array.isArray(data)||!data.length)throw Error();products=data.filter(x=>x.name).map(x=>({code:String(x.code||x.I_Code||''),name:String(x.name||x.I_Name||''),wholesale:Number(x.wholesale??x.I_S_Price_W??0),retail:Number(x.retail??x.I_S_Price_N??0)}));localStorage.setItem(PRODKEY,JSON.stringify(products));toast(`تم استيراد ${products.length.toLocaleString('ar-EG')} منتج`)}catch(e){toast('صيغة الملف غير صحيحة')}}
function parseCsv(t){const out=[];let row=[],cell='',q=false;for(let i=0;i<t.length;i++){const c=t[i];if(c==='"')q=!q;else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(cell||row.length){row.push(cell);out.push(row);row=[];cell=''}}else cell+=c}if(cell||row.length){row.push(cell);out.push(row)}return out.slice(1)}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
els.search.addEventListener('input',renderSuggestions);els.search.addEventListener('keydown',e=>{const list=[...els.suggestions.querySelectorAll('.suggestion[data-index]')];if(e.key==='ArrowDown'){e.preventDefault();activeSuggestion=Math.min(activeSuggestion+1,list.length-1);list.forEach((x,i)=>x.classList.toggle('active',i===activeSuggestion))}else if(e.key==='ArrowUp'){e.preventDefault();activeSuggestion=Math.max(activeSuggestion-1,0);list.forEach((x,i)=>x.classList.toggle('active',i===activeSuggestion))}else if(e.key==='Enter'&&activeSuggestion>=0){e.preventDefault();list[activeSuggestion]?.dispatchEvent(new MouseEvent('mousedown'))}else if(e.key==='Escape')els.suggestions.classList.remove('open')});document.addEventListener('click',e=>{if(!e.target.closest('.product-search'))els.suggestions.classList.remove('open')});document.querySelectorAll('.price-btn').forEach(b=>b.addEventListener('click',()=>{if(cart.length){toast('لا يمكن تغيير النظام بعد إضافة المنتجات');return}priceMode=b.dataset.price;updatePrice()}));$('#addProduct').addEventListener('click',add);els.qty.addEventListener('keydown',e=>{if(e.key==='Enter')add()});$('#saveInvoice').addEventListener('click',save);$('#printInvoice').addEventListener('click',()=>window.print());$('#newInvoice').addEventListener('click',newInvoice);$('#exportData').addEventListener('click',exportData);$('#customerCode').addEventListener('input',e=>renderCustomer(e.target.value));document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='p'){e.preventDefault();window.print()}if(e.ctrlKey&&e.key.toLowerCase()==='s'){e.preventDefault();save()}if(e.ctrlKey&&e.key.toLowerCase()==='n'){e.preventDefault();newInvoice()}if(e.key==='Delete'&&document.activeElement.classList.contains('line-qty')){const i=Number(document.activeElement.dataset.i);cart.splice(i,1);renderCart()}});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}});setDate();loadProducts();loadCustomers();renderCart();renderSaved();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
